# Generated by Django 4.2.8 on 2023-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена за покупку'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_version', models.IntegerField(blank=True, null=True, verbose_name='Номер версии')),
                ('name_version', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название версии')),
                ('version_flag', models.BooleanField(default=False, verbose_name='Прикнак активности')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
